/* Lexiques par langue : marqueurs typiques de l'IA, connecteurs, réécritures. */
(function () {
  const D = (window.DIA = window.DIA || {});

  D.LEX = {
    fr: {
      name: 'Français',
      stopwords: ['le', 'la', 'les', 'de', 'des', 'du', 'et', 'est', 'un', 'une', 'que', 'qui', 'dans', 'pour',
        'pas', 'sur', 'au', 'aux', 'il', 'elle', 'nous', 'vous', 'ils', 'elles', 'ce', 'cette', 'ces', 'sont', 'avec',
        'plus', 'par', 'mais', 'ou', 'ne', 'se', 'son', 'sa', 'ses', 'leur', 'leurs', 'été', 'être', 'comme',
        'tout', 'aussi', 'très', 'je', 'on', 'cela', 'ça', 'mon', 'ma', 'mes', 'était', 'avoir', 'fait', 'bien'],

      // Expressions fortement associées aux textes générés (poids 1)
      strong: [
        'il est important de noter', 'il est important de souligner', 'il convient de noter', 'il est à noter que',
        'il est essentiel de', 'il est essentiel que', 'il est crucial de', 'il est indéniable que', 'force est de constater',
        "dans le monde d'aujourd'hui", 'dans le monde actuel', "à l'ère du numérique", "à l'ère numérique",
        'dans un monde en constante évolution', 'en constante évolution', 'joue un rôle crucial', 'joue un rôle essentiel',
        'joue un rôle clé', 'joue un rôle prépondérant', 'jouent un rôle crucial', 'jouent un rôle essentiel',
        'jouent un rôle clé', 'un rôle crucial', 'plonger dans', 'plongeons dans', 'tapisserie', 'témoigne de',
        'témoignent de', 'un témoignage de', 'tirer parti de', 'tirer pleinement parti de', 'un large éventail de',
        'une multitude de', 'une myriade de', 'une pléthore de', "n'hésitez pas à", 'relever les défis', 'ouvre la voie à',
        'ouvrir la voie à', 'ouvrent la voie à', 'approche holistique', 'holistique', 'synergie', 'mettre en lumière',
        'met en lumière', 'mettent en lumière', "souligne l'importance de", 'levier incontournable', 'incontournable',
        'incontournables', 'primordial', 'primordiale', 'révolutionner', 'en fin de compte', 'de manière significative',
        'indéniablement', 'un véritable', 'une véritable', 'au cœur de', 'en conclusion', 'en résumé', 'pour conclure',
        'naviguer dans', 'paysage numérique', 'un atout majeur', 'un enjeu majeur'
      ],
      // Mots courants mais sur-représentés chez les IA (poids 0,4)
      weak: [
        'crucial', 'cruciale', 'cruciaux', 'cruciales', 'optimiser', 'favoriser', 'favorise', 'favorisent', 'levier',
        'robuste', 'robustes', 'considérablement', 'véritablement', 'afin de', "afin d'", 'par conséquent',
        'en somme', "dans l'ensemble", 'en outre', 'de surcroît'
      ],

      transitions: {
        add: ['de plus', 'en outre', 'par ailleurs', 'de surcroît', 'également', 'qui plus est'],
        contrast: ['cependant', 'néanmoins', 'toutefois', 'en revanche'],
        cause: ['ainsi', 'par conséquent', 'en effet', 'effectivement', 'dès lors', 'de ce fait'],
        conclude: ['en conclusion', 'en résumé', 'pour conclure', 'en somme', "dans l'ensemble", 'en définitive',
          'finalement', 'en fin de compte', 'pour résumer'],
        sequence: ["tout d'abord", 'premièrement', 'deuxièmement', 'troisièmement', 'enfin', "d'une part", "d'autre part"]
      },
      transitionAlts: {
        add: { casual: ['Et puis, ', 'Aussi, ', 'Et '], neutral: ['Aussi, ', 'Et ', ''], pro: ['Autre point : ', ''], academic: ['De même, ', ''] },
        contrast: { casual: ['Mais ', 'Par contre, '], neutral: ['Mais ', 'Pourtant, '], pro: ['Pourtant, ', 'Mais '], academic: ['Pourtant, ', 'Toutefois, '] },
        cause: { casual: ['Du coup, ', 'Donc ', ''], neutral: ['Donc ', ''], pro: ['Donc ', ''], academic: ['Dès lors, ', ''] },
        conclude: { casual: ['Bref, ', 'Au final, ', 'En gros, '], neutral: ['Bref, ', 'Au final, '], pro: ['Au final, ', 'Pour résumer, '], academic: ['Pour finir, ', 'En définitive, '] },
        sequence: { casual: [''], neutral: [''], pro: [''], academic: [''] }
      },

      personal: /(?<![\p{L}])(?:j['’]|m['’](?=\p{L})|(?:je|moi|mon|ma|mes|perso|franchement|bref|genre|truc|ouais|bah|hein|du coup|bon)(?![\p{L}]))/giu,
      triplet: /,\s[^,.;:!?\n]{1,40},?\s(?:et|ou)\s/iu,

      // Réécritures : clé = expression (minuscules), d = alternatives par défaut, c = ton décontracté
      replacements: {
        'il est important de noter que': { d: ['notons que', ''], c: ['', 'faut savoir que'] },
        'il est important de souligner que': { d: ['notons que', ''] },
        'il convient de noter que': { d: ['notons que', ''] },
        'il est à noter que': { d: ['notons que', ''] },
        'il est essentiel de': { d: ['il faut'], c: ['il faut', 'on doit'] },
        'il est essentiel que': { d: ['il faut que'] },
        'il est crucial de': { d: ['il faut', 'il vaut mieux'] },
        'il est indéniable que': { d: ['il est clair que'], c: ['clairement,'] },
        'force est de constater que': { d: ['il faut bien admettre que'], c: ['on voit bien que'] },
        "dans le monde d'aujourd'hui": { d: ["aujourd'hui", 'de nos jours'] },
        'dans le monde actuel': { d: ["aujourd'hui", 'de nos jours'] },
        "à l'ère du numérique": { d: ["aujourd'hui", 'avec le numérique'] },
        "à l'ère numérique": { d: ["aujourd'hui", 'avec le numérique'] },
        'dans un monde en constante évolution': { d: ["aujourd'hui"], c: ['dans un monde qui bouge vite'] },
        'en constante évolution': { d: ['qui évolue vite', 'qui change sans cesse'], c: ['qui bouge tout le temps'] },
        'joue un rôle crucial': { d: ['a un rôle décisif', 'compte beaucoup'], c: ['compte beaucoup', 'pèse lourd'] },
        'joue un rôle essentiel': { d: ['a un rôle décisif', 'compte beaucoup'] },
        'joue un rôle clé': { d: ['tient une place centrale', 'compte beaucoup'] },
        'joue un rôle prépondérant': { d: ['pèse lourd', 'compte beaucoup'] },
        'jouent un rôle crucial': { d: ['ont un rôle décisif', 'comptent beaucoup'] },
        'jouent un rôle essentiel': { d: ['ont un rôle décisif', 'comptent beaucoup'] },
        'jouent un rôle clé': { d: ['tiennent une place centrale', 'comptent beaucoup'] },
        'un rôle crucial': { d: ['un rôle important', 'un vrai rôle'] },
        'plonger dans': { d: ['se pencher sur', 'regarder de près'] },
        'plongeons dans': { d: ['regardons', 'penchons-nous sur'] },
        'une riche tapisserie de': { d: ['un mélange de', 'tout un ensemble de'] },
        'tapisserie': { d: ['mosaïque', 'mélange'] },
        'témoigne de': { d: ['montre', 'prouve'] },
        'témoignent de': { d: ['montrent', 'prouvent'] },
        'un témoignage de': { d: ['une preuve de'] },
        'tirer pleinement parti de': { d: ['profiter vraiment de'] },
        'tirer parti de': { d: ['profiter de', 'utiliser'] },
        'favoriser': { d: ['encourager', 'stimuler'] },
        'favorise': { d: ['encourage', 'stimule'] },
        'favorisent': { d: ['encouragent', 'stimulent'] },
        'optimiser': { d: ['améliorer'] },
        'un large éventail de': { d: ['beaucoup de', 'toute une série de'], c: ['plein de'] },
        'une multitude de': { d: ['beaucoup de', 'de nombreuses'], c: ['plein de', 'tout un tas de'] },
        'une myriade de': { d: ['beaucoup de', 'énormément de'] },
        'une pléthore de': { d: ['beaucoup de', 'énormément de'] },
        'en fin de compte': { d: ['au final', 'finalement'] },
        "n'hésitez pas à": { d: ['vous pouvez', 'pensez à'] },
        'mettre en lumière': { d: ['montrer', 'faire ressortir'] },
        'met en lumière': { d: ['montre', 'fait ressortir'] },
        'mettent en lumière': { d: ['montrent', 'font ressortir'] },
        "souligne l'importance de": { d: ["montre l'intérêt de", "rappelle l'intérêt de"] },
        'de manière significative': { d: ['nettement', 'beaucoup'] },
        'de manière efficace': { d: ['efficacement', 'bien'] },
        'considérablement': { d: ['nettement', 'beaucoup'] },
        'indéniablement': { d: ['clairement', 'sans doute'] },
        'levier incontournable': { d: ['atout indispensable', 'outil clé'] },
        'incontournable': { d: ['indispensable', 'majeur'] },
        'incontournables': { d: ['indispensables', 'majeurs'] },
        'primordial': { d: ['capital', 'très important'] },
        'primordiale': { d: ['capitale', 'très importante'] },
        'crucial': { d: ['important', 'déterminant'] },
        'cruciale': { d: ['importante', 'déterminante'] },
        'cruciaux': { d: ['importants', 'déterminants'] },
        'cruciales': { d: ['importantes', 'déterminantes'] },
        'robuste': { d: ['solide'] },
        'robustes': { d: ['solides'] },
        'révolutionner': { d: ['transformer', 'changer en profondeur'] },
        'relever les défis': { d: ['régler les problèmes', "s'attaquer aux problèmes"] },
        'ouvrir la voie à': { d: ['annoncer', 'préparer le terrain pour'] },
        'ouvre la voie à': { d: ['annonce', 'prépare le terrain pour'] },
        'ouvrent la voie à': { d: ['annoncent', 'préparent le terrain pour'] },
        'au cœur de': { d: ['au centre de'] },
        'une approche holistique': { d: ['une approche globale', "une vue d'ensemble"] },
        'synergie': { d: ['collaboration'] },
        'en somme': { d: ['bref', 'en gros'] },
        "dans l'ensemble": { d: ['globalement'], c: ['en gros'] },
        'un véritable': { d: ['un vrai'] },
        'une véritable': { d: ['une vraie'] },
        'véritablement': { d: ['vraiment'] },
        'afin de': { d: ['pour'] },
        "afin d'": { d: ['pour '] },
        'par conséquent': { d: ['donc'], c: ['du coup'] },
        'en outre': { d: ['aussi'] },
        'de surcroît': { d: ['en plus'] },
        'naviguer dans': { d: ['se repérer dans', "s'y retrouver dans"] },
        'paysage numérique': { d: ['monde du numérique'] },
        'un atout majeur': { d: ['un vrai plus', 'un gros avantage'] },
        'un enjeu majeur': { d: ['une vraie question', 'un sujet important'] },
        'levier': { d: ['atout', 'moyen'] }
      },
      casualSubs: [
        [/(?<![\p{L}])cela(?![\p{L}])/gu, 'ça'], [/(?<![\p{L}])Cela(?![\p{L}])/gu, 'Ça'],
        [/(?<![\p{L}])nous pouvons(?![\p{L}])/giu, 'on peut'], [/(?<![\p{L}])nous devons(?![\p{L}])/giu, 'on doit'],
        [/(?<![\p{L}])nous allons(?![\p{L}])/giu, 'on va'], [/(?<![\p{L}])nous avons(?![\p{L}])/giu, 'on a'],
        [/(?<![\p{L}])nous sommes(?![\p{L}])/giu, 'on est'], [/(?<![\p{L}])nous voyons(?![\p{L}])/giu, 'on voit']
      ],
      splitters: [
        { re: /, mais /, kind: 'but', word: 'Mais' },
        { re: /, et /, kind: 'and', word: 'Et' },
        { re: / ?; /, kind: 'semi' },
        { re: /, ce qui /, kind: 'which', word: 'Cela', casual: 'Ça' },
        { re: /, donc /, kind: 'so', word: 'Donc' }
      ],
      mergeable: ['il', 'elle', 'ils', 'elles', 'on', 'le', 'la', 'les', 'ce', 'cette', 'ces', "c'est", 'cela', 'ça',
        'un', 'une', 'des', 'son', 'sa', 'ses', 'leur', 'leurs', 'nous', 'vous', 'je'],
      mergeJoin: { casual: ', et ', neutral: ', et ', pro: ' ; ', academic: ' ; ' }
    },

    en: {
      name: 'English',
      stopwords: ['the', 'of', 'and', 'to', 'is', 'in', 'that', 'it', 'for', 'was', 'on', 'are', 'with', 'as', 'this',
        'be', 'by', 'at', 'have', 'from', 'or', 'but', 'not', 'they', 'we', 'you', 'an', 'which', 'their', 'has',
        'would', 'can', 'will', 'there', 'been', 'more', 'if', 'about', 'what', 'its', 'i', 'my', 'so', 'just', 'were'],

      strong: [
        'delve', 'delves', 'delving', 'delve into', 'tapestry', 'testament to', 'it is important to note',
        "it's important to note", 'it is worth noting', "it's worth noting", 'it is essential to', 'it is crucial to',
        "in today's fast-paced world", "in today's digital age", 'in the digital age', "in today's world", 'ever-evolving',
        'ever-changing', 'plays a crucial role', 'plays a pivotal role', 'plays a vital role', 'plays a key role',
        'play a crucial role', 'play a pivotal role', 'play a vital role', 'pivotal', 'seamless', 'seamlessly', 'leverage',
        'leveraging', 'leverages', 'holistic', 'multifaceted', 'intricacies', 'navigate the complexities',
        'the realm of', 'realm', 'landscape', 'foster', 'fostering', 'fosters', 'showcase', 'showcasing', 'showcases',
        'underscore', 'underscores', 'embark on', 'unlock the potential', 'unlock their full potential',
        'harness the power of', 'transformative', 'game-changer', 'cutting-edge', 'groundbreaking', 'paramount',
        'a myriad of', 'myriad', 'a plethora of', 'meticulous', 'meticulously', 'vibrant', 'bustling', 'commendable',
        'in conclusion', 'in summary', 'at the end of the day', 'when it comes to', 'stands as a', 'serves as a',
        'strike a balance', 'drive innovation', 'streamline', 'empower', 'empowers', 'empowering', 'elevate',
        'a rich tapestry', 'ever evolving', 'navigating'
      ],
      weak: [
        'crucial', 'vital', 'robust', 'comprehensive', 'intricate', 'navigate', 'enhance', 'enhances', 'enhancing',
        'utilize', 'utilizes', 'utilizing', 'notably', 'a wide range of', 'a variety of', 'in order to', 'embrace',
        'thrive', 'unlock', 'harness'
      ],

      transitions: {
        add: ['furthermore', 'moreover', 'additionally', 'in addition', 'also', 'besides'],
        contrast: ['however', 'nevertheless', 'nonetheless', 'conversely', 'on the other hand'],
        cause: ['therefore', 'thus', 'consequently', 'hence', 'as a result', 'indeed', 'in fact'],
        conclude: ['in conclusion', 'in summary', 'to summarize', 'overall', 'ultimately', 'all in all', 'in essence', 'to sum up'],
        sequence: ['firstly', 'first and foremost', 'secondly', 'thirdly', 'lastly', 'finally', 'notably', 'importantly', 'interestingly']
      },
      transitionAlts: {
        add: { casual: ['Plus, ', 'Also, ', 'And '], neutral: ['Also, ', 'And ', ''], pro: ['Also, ', ''], academic: ['Further, ', ''] },
        contrast: { casual: ['But ', 'Still, '], neutral: ['But ', 'Still, '], pro: ['Still, ', 'But '], academic: ['Still, ', 'Yet '] },
        cause: { casual: ['So ', ''], neutral: ['So ', ''], pro: ['So ', ''], academic: ['As a result, ', ''] },
        conclude: { casual: ['So, ', 'Anyway, ', 'In short, '], neutral: ['In short, ', 'All in all, '], pro: ['In short, ', 'All told, '], academic: ['In short, ', 'To conclude, '] },
        sequence: { casual: [''], neutral: [''], pro: [''], academic: [''] }
      },

      personal: /(?<![\p{L}])(?:i|me|my|mine|myself|i['’]m|i['’]ve|i['’]d|i['’]ll|honestly|kinda|gonna|wanna|yeah|stuff|lol|pretty much)(?![\p{L}])|\p{L}(?:n['’]t|['’]re|['’]ve|['’]ll|['’]m)(?![\p{L}])/giu,
      triplet: /,\s[^,.;:!?\n]{1,40},?\s(?:and|or)\s/iu,

      replacements: {
        'it is important to note that': { d: ['', 'note that'], c: ['', 'keep in mind that'] },
        "it's important to note that": { d: ['', 'note that'], c: ['', 'keep in mind that'] },
        'it is worth noting that': { d: ['', 'note that'] },
        "it's worth noting that": { d: ['', 'note that'] },
        'it is essential to': { d: ['we need to', 'it is key to'], c: ['you need to', "you've got to"] },
        'it is crucial to': { d: ['we need to', 'it is key to'], c: ['you need to', "you've got to"] },
        "in today's fast-paced world": { d: ['today', 'these days'] },
        "in today's digital age": { d: ['today', 'nowadays'] },
        'in the digital age': { d: ['today', 'nowadays'] },
        "in today's world": { d: ['today', 'these days'] },
        'ever-evolving': { d: ['changing', 'fast-moving'] },
        'ever evolving': { d: ['changing', 'fast-moving'] },
        'ever-changing': { d: ['changing', 'shifting'] },
        'plays a crucial role in': { d: ['is key to', 'is central to'], c: ['matters a lot for', 'is a big part of'] },
        'plays a pivotal role in': { d: ['is key to', 'is central to'], c: ['matters a lot for'] },
        'plays a vital role in': { d: ['is key to', 'is central to'], c: ['matters a lot for'] },
        'plays a key role in': { d: ['is central to'], c: ['is a big part of'] },
        'play a crucial role in': { d: ['are key to', 'are central to'], c: ['matter a lot for'] },
        'play a pivotal role in': { d: ['are key to', 'are central to'] },
        'play a vital role in': { d: ['are key to', 'are central to'] },
        'delve into': { d: ['look at', 'explore'], c: ['dig into'] },
        'delves into': { d: ['looks at', 'explores'], c: ['digs into'] },
        'delving into': { d: ['looking at', 'exploring'], c: ['digging into'] },
        'delve': { d: ['dig'] },
        'a rich tapestry of': { d: ['a mix of', 'a blend of'] },
        'tapestry': { d: ['mix'] },
        'is a testament to': { d: ['shows', 'proves'] },
        'a testament to': { d: ['proof of', 'a sign of'] },
        'leverage': { d: ['use', 'make use of'] },
        'leveraging': { d: ['using'] },
        'leverages': { d: ['uses'] },
        'utilize': { d: ['use'] }, 'utilizes': { d: ['uses'] }, 'utilizing': { d: ['using'] },
        'seamless': { d: ['smooth'] }, 'seamlessly': { d: ['smoothly'] },
        'robust': { d: ['solid', 'strong'] },
        'comprehensive': { d: ['complete', 'thorough'] },
        'pivotal': { d: ['key', 'central'] },
        'crucial': { d: ['key', 'important'] },
        'vital': { d: ['key', 'essential'] },
        'a variety of': { d: ['all sorts of', 'different'] },
        'paramount': { d: ['essential', 'critical'] },
        'a myriad of': { d: ['lots of', 'many'] }, 'myriad': { d: ['countless'] },
        'a plethora of': { d: ['plenty of', 'a lot of'] },
        'a wide range of': { d: ['all kinds of', 'many'] },
        'a wide array of': { d: ['all kinds of', 'many'] },
        'a wide variety of': { d: ['all kinds of', 'many'] },
        'navigate the complexities of': { d: ['deal with', 'handle'] },
        'navigate': { d: ['handle', 'get through'] },
        'navigating': { d: ['handling', 'dealing with'] },
        'the landscape of': { d: ['the world of'] },
        'landscape': { d: ['scene', 'field'] },
        'the realm of': { d: ['the world of', 'the field of'] },
        'realm': { d: ['area', 'field'] },
        'foster': { d: ['build', 'encourage'] }, 'fostering': { d: ['building', 'encouraging'] }, 'fosters': { d: ['builds', 'encourages'] },
        'showcase': { d: ['show'] }, 'showcases': { d: ['shows'] }, 'showcasing': { d: ['showing'] },
        'underscore': { d: ['show', 'highlight'] }, 'underscores': { d: ['shows', 'highlights'] },
        'embark on a journey': { d: ['start'] }, 'embark on': { d: ['start', 'begin'] },
        'unlock their full potential': { d: ['reach their potential', 'do their best work'] },
        'unlock the potential of': { d: ['get the most out of'] },
        'unlock': { d: ['open up'] },
        'harness the power of': { d: ['use', 'make the most of'] },
        'harness': { d: ['use'] },
        'elevate': { d: ['improve', 'boost'] },
        'empower': { d: ['help', 'enable'] }, 'empowers': { d: ['helps', 'enables'] }, 'empowering': { d: ['helping'] },
        'enhance': { d: ['improve', 'boost'] }, 'enhances': { d: ['improves', 'boosts'] }, 'enhancing': { d: ['improving'] },
        'streamline': { d: ['simplify', 'speed up'] },
        'transformative': { d: ['major', 'big'] },
        'game-changer': { d: ['big deal', 'major shift'] },
        'cutting-edge': { d: ['modern', 'latest'] },
        'groundbreaking': { d: ['new', 'original'] },
        'meticulous': { d: ['careful'] }, 'meticulously': { d: ['carefully'] },
        'vibrant': { d: ['lively'] }, 'bustling': { d: ['busy'] },
        'intricate': { d: ['complex', 'detailed'] }, 'intricacies': { d: ['details', 'ins and outs'] },
        'multifaceted': { d: ['complex', 'many-sided'] },
        'a holistic approach': { d: ['a big-picture approach', 'a broader approach'] },
        'holistic': { d: ['overall', 'whole'] },
        'in order to': { d: ['to'] },
        'due to the fact that': { d: ['because'] },
        'at the end of the day': { d: ['in the end'] },
        'when it comes to': { d: ['with', 'as for'] },
        'serves as a': { d: ['is a', 'works as a'] },
        'stands as a': { d: ['is a'] },
        'commendable': { d: ['impressive', 'admirable'] },
        'notably': { d: ['especially'] },
        'strike a balance between': { d: ['balance', 'find a middle ground between'] },
        'drive innovation': { d: ['spark new ideas', 'push new ideas'] },
        'thrive': { d: ['do well', 'grow'] },
        'embrace': { d: ['adopt', 'take on'] }
      },
      contractions: {
        neg: [['do not', "don't"], ['does not', "doesn't"], ['did not', "didn't"], ['is not', "isn't"], ['are not', "aren't"],
          ['was not', "wasn't"], ['were not', "weren't"], ['cannot', "can't"], ['will not', "won't"], ['would not', "wouldn't"],
          ['should not', "shouldn't"], ['could not', "couldn't"], ['have not', "haven't"], ['has not', "hasn't"]],
        other: [['it is', "it's"], ['that is', "that's"], ['there is', "there's"], ['I am', "I'm"], ['we are', "we're"],
          ['they are', "they're"], ['you are', "you're"], ['let us', "let's"]],
        casual: [['it will', "it'll"], ['we will', "we'll"], ['you will', "you'll"], ['they will', "they'll"], ['we have', "we've"]]
      },
      splitters: [
        { re: /, but /, kind: 'but', word: 'But' },
        { re: /, and /, kind: 'and', word: 'And' },
        { re: /; /, kind: 'semi' },
        { re: /, which /, kind: 'which', word: 'This' },
        { re: /, so /, kind: 'so', word: 'So' }
      ],
      mergeable: ['it', 'this', 'that', 'these', 'those', 'they', 'he', 'she', 'we', 'you', 'the', 'a', 'an', 'its',
        'their', 'his', 'her', 'there'],
      mergeJoin: { casual: ', and ', neutral: ', and ', pro: '; ', academic: '; ' }
    }
  };
})();
